name: technology_config
description: This hybrid plant produces ammonia
technologies:
  PEM_fuel_cell:
    performance_model:
      model: PEMH2FuelCellPerformanceModel
    cost_model:
      model: GenericConverterCostModel
    model_inputs:
      performance_parameters:
        system_capacity_kw: 1500
        n_stacks: 60
        stack_temperature_K: 278  # Not used yet
        hhv: 39.4  # kWh/kg
      cost_parameters:
        commodity: electricity
        commodity_rate_units: kW
        commodity_amount_units: kW*h
        unit_capex: 1999.6  # USD/kW
        unit_opex: 31  # USD/kW/year
        unit_varopex: 0.0  # USD/kWh
        cost_year: 2026
  electricity_load_demand:
    performance_model:
      model: GenericDemandComponent
    model_inputs:
      performance_parameters:
        commodity: electricity
        commodity_rate_units: kW
        demand_profile: 1000
  h2_feedstock:
    performance_model:
      model: FeedstockPerformanceModel
    cost_model:
      model: FeedstockCostModel
    model_inputs:
      shared_parameters:
        commodity: hydrogen
        commodity_rate_units: kg/h
      performance_parameters:
        rated_capacity: 50.0  # kg/h of hydrogen
      cost_parameters:
        cost_year: 2022
        price: 5.0
        annual_cost: 0.
        start_up_cost: 0.0
  o2_feedstock:
    performance_model:
      model: FeedstockPerformanceModel
    cost_model:
      model: FeedstockCostModel
    model_inputs:
      shared_parameters:
        commodity: oxygen
        commodity_rate_units: kg/h
      performance_parameters:
        rated_capacity: 400.0  # kg/h of oxygen
      cost_parameters:
        cost_year: 2022
        price: 0.5  # $5/kg of oxygen. price is extremely variable
        annual_cost: 0.
        start_up_cost: 0.0
