name: technology_config
description: This hybrid plant produces ammonia
technologies:
  PEM_fuel_cell:
    performance_model:
      model: PEMH2FuelCellPerformanceModel
    cost_model:
      model: PEMH2FuelCellCostModel
    model_inputs:
      shared_parameters:
        system_capacity_kw: 1500
      performance_parameters:
        n_stacks: 60
        stack_temperature_K: 278  # Not used yet
        hhv: 39.4  # kWh/kg
      cost_parameters:
        capex_stack_per_kw: 800
        capex_hydrogen_supply_per_kw: 140.67
        capex_air_supply_per_kw: 138.79
        capex_cooling_per_kw: 64.14
        capex_controls_instrumentation_per_kw: 106.52
        capex_electrical_per_kw: 447.83
        capex_assembly_per_kw: 63.51
        capex_additional_labor_per_kw: 137.96
        fixed_opex_per_kw_per_year: 31
        cost_year: 2026
  electricity_load_demand:
    performance_model:
      model: GenericDemandComponent
    model_inputs:
      performance_parameters:
        commodity: electricity
        commodity_rate_units: kW
        demand_profile: 1000
  h2_feedstock:
    performance_model:
      model: FeedstockPerformanceModel
    cost_model:
      model: FeedstockCostModel
    model_inputs:
      shared_parameters:
        commodity: hydrogen
        commodity_rate_units: kg/h
      performance_parameters:
        rated_capacity: 50.0  # kg/h of hydrogen
      cost_parameters:
        cost_year: 2022
        price: 5.0
        annual_cost: 0.
        start_up_cost: 0.0
  o2_feedstock:
    performance_model:
      model: FeedstockPerformanceModel
    cost_model:
      model: FeedstockCostModel
    model_inputs:
      shared_parameters:
        commodity: oxygen
        commodity_rate_units: kg/h
      performance_parameters:
        rated_capacity: 400.0  # kg/h of oxygen
      cost_parameters:
        cost_year: 2022
        price: 0.5  # $5/kg of oxygen. price is extremely variable
        annual_cost: 0.
        start_up_cost: 0.0
