name: technology_config
description: This hybrid plant produces ammonia
technologies:
  SONG_fuel_cell:
    performance_model:
      model: SONGFuelCellPerformanceModel
    cost_model:
      model: SONGFuelCellCostModel
    model_inputs:
      shared_parameters:
        system_capacity_kw: 1500
      performance_parameters:
        n_stacks: 60
        stack_temperature_K: 1073
        hhv: 15.4  # kWh/kg --> based on methane
      cost_parameters:
        capex_stack_per_kw: 800
        capex_fuel_supply_per_kw: 140.67
        capex_air_supply_per_kw: 138.79
        capex_cooling_per_kw: 64.14
        capex_controls_instrumentation_per_kw: 106.52
        capex_electrical_per_kw: 447.83
        capex_assembly_per_kw: 63.51
        capex_additional_labor_per_kw: 137.96
        fixed_opex_per_kw_per_year: 31
        cost_year: 2026
  electricity_load_demand:
    performance_model:
      model: GenericDemandComponent
    model_inputs:
      performance_parameters:
        commodity: electricity
        commodity_rate_units: kW
        demand_profile: 1000
  ng_feedstock:
    performance_model:
      model: FeedstockPerformanceModel
    cost_model:
      model: FeedstockCostModel
    model_inputs:
      shared_parameters:
        commodity: natural_gas
        commodity_rate_units: MMBtu/h
      performance_parameters:
        rated_capacity: 20.0  # MMBtu/h of natural gas
      cost_parameters:
        cost_year: 2022
        price: 0.1
        annual_cost: 0.
        start_up_cost: 0.0
  o2_feedstock:
    performance_model:
      model: FeedstockPerformanceModel
    cost_model:
      model: FeedstockCostModel
    model_inputs:
      shared_parameters:
        commodity: oxygen
        commodity_rate_units: kg/h
      performance_parameters:
        rated_capacity: 400.0  # kg/h of oxygen
      cost_parameters:
        cost_year: 2022
        price: 0.5  # $0.5/kg of oxygen. price is extremely variable
        annual_cost: 0.
        start_up_cost: 0.0
